apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argocd-html-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/koushiksiripuram/html-argocd-css.git
    targetRevision: HEAD
    path: dev   # or "." if files are in root

  destination: 
    server: https://kubernetes.default.svc
    namespace: html-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
