apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-argocd
spec:
  selector:
    matchLabels:
      app: html-argocd
  replicas: 3
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
      - name: html-argocd
        image: koushiksiripuram/html-argocd:1.0
        ports:
        - containerPort: 80
